[package]
name = "phira"
version = "0.1.0"

[android]
activity = "com.phira.MainActivity"
app_name = "Phira"
package = "com.phira"
icon = "@mipmap/ic_launcher"

[android.permissions]
INTERNET = true

[[android.meta_data]]
name = "android.app.lib_name"
value = "phira"